### ISSUE TITLE
im sponsoring but cant ghet access to any of the things on my tier

### ISSUE THREAD

**Issue by justfly1111** [zdharma-continuum/hacking-private#1]
i just sponsopred you through the zinit wiki and i cant access any of the extras that are supposed to be included with my tier the $15/.month one which includes the ZTES and the extra themes extra can you please help sort this out for me after sponsoring all the links are either 404 errors or goes to an asciicast thhank yhou so much!

**Comment by pschmitt** [comment]
Erm, this is awkward. psprint is no longer involved with zinit or any other zdharma-continuum project.
You might want to cancel your membership.

What link did you follow that led you to the sponsorship page?
